#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "Welcome to the Python Powered Linux distro!"
exec /bin/python3 /usr/bin/userspace-v1/init/init.py

echo "If you see this message, it means that the kernel is going to kernel panic since the script has died and if the pid 0 process dies the kernel will panic"
